---
- name: Check for security updates on Rocky Linux 8
  hosts: all
  become: true

  tasks:
    - name: List available security updates
      shell: dnf updateinfo list security
      register: security_updates
      changed_when: false

    - name: Show security updates
      debug:
        var: security_updates.stdout_lines
